<?xml version="1.0" encoding="utf-8" ?>
<!-- 约束 -->
<!DOCTYPE students [
        <!ELEMENT students (student*)>
        <!ELEMENT student (name, age, sex)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT age (#PCDATA)>
        <!ELEMENT sex (#PCDATA)>
        <!ATTLIST student number ID #REQUIRED>
        ]>

<students>
    <student number="s1">
        <name>Jack</name>
        <age>28</age>
        <sex>男</sex>
    </student>

    <student number="s2">
        <name>Jack</name>
        <age>28</age>
        <sex>男</sex>
    </student>
</students>